-- This migration was replaced with runtime initialization.
-- 
-- Default cause_reasons and nodeset data are now loaded from embedded JSON files
-- at application startup via db::defaults::initialize_defaults().
--
-- This approach avoids issues with large SQL migrations on slow devices
-- and SQLite statement parsing with embedded semicolons in JSON data.
--
-- See: defaults/cause_reasons.json and defaults/default_nodeset.json
