use serde::Serialize;
use sqlx::prelude::FromRow;

#[derive(Debug, FromRow, Serialize)]
pub struct AcAction {
    pub id: i32,
    pub action_timestamp: i32, // Unix timestamp
    pub device_identifier: String,
    pub action_type: String, // on, off, toggle-powerful
    pub mode: Option<i32>,
    pub fan_speed: Option<i32>,
    pub request_temperature: Option<f32>,
    pub swing: Option<i32>,
    pub measured_temperature: Option<f32>,
    pub measured_net_power_watt: Option<i32>,
    pub is_human_home: Option<bool>,
}

impl AcAction {
    /// Create a new AC action for insertion into the database (without id)
    pub fn new_for_insert(
        device_identifier: String,
        action_type: String,
        mode: Option<i32>,
        fan_speed: Option<i32>,
        request_temperature: Option<f32>,
        swing: Option<i32>,
        measured_temperature: Option<f32>,
        measured_net_power_watt: Option<i32>,
        is_human_home: Option<bool>,
    ) -> Self {
        Self {
            id: 0, // Will be auto-generated by database
            action_timestamp: chrono::Utc::now().timestamp() as i32,
            device_identifier,
            action_type,
            mode,
            fan_speed,
            request_temperature,
            swing,
            measured_temperature,
            measured_net_power_watt,
            is_human_home,
        }
    }
}
